[features]
seeds = false
skip-lint = false
[programs.localnet]
meme_race = "3uEYaDAsPToBcGM4iYopi4yM7Q7DJHfnprvzvKEqEvmJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mrmizz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
